batch_size = 1
boundary_th = 0.5
ce = True
ce_weight = 1.0
class_weight = True
csv_dir='./backbones/asrf/csv'
dampening = 0.0
dataset_root = './dataset'
model_root = './model'
result_root ='./result'
record_root = './record'
focal = False
focal_weight = 1.0
gstmse = True
gstmse_index = 'feature'
gstmse_weight = 1.0
in_channel = 2048
iou_thresholds = [0.1, 0.25, 0.5]
lambda_b = 0.1
learning_rate = 0.0005
max_epoch = 50
momentum = 0.9
n_features = 64
n_layers = 10
n_stages = 4
n_stages_asb = 4
n_stages_brb = 4
nesterov = True
param_search = False
tmse = False
tmse_weight= 0.15
tolerance= 5
weight_decay= 0.0001

